/* 
 * paccurate.io
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BoxProperties
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BoxPropertiesTests
    {
        // TODO uncomment below to declare an instance variable for BoxProperties
        //private BoxProperties instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BoxProperties
            //instance = new BoxProperties();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BoxProperties
        /// </summary>
        [Test]
        public void BoxPropertiesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BoxProperties
            //Assert.IsInstanceOfType<BoxProperties> (instance, "variable 'instance' is a BoxProperties");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RefId'
        /// </summary>
        [Test]
        public void RefIdTest()
        {
            // TODO unit test for the property 'RefId'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'WeightTare'
        /// </summary>
        [Test]
        public void WeightTareTest()
        {
            // TODO unit test for the property 'WeightTare'
        }
        /// <summary>
        /// Test the property 'WeightMax'
        /// </summary>
        [Test]
        public void WeightMaxTest()
        {
            // TODO unit test for the property 'WeightMax'
        }
        /// <summary>
        /// Test the property 'Dimensions'
        /// </summary>
        [Test]
        public void DimensionsTest()
        {
            // TODO unit test for the property 'Dimensions'
        }
        /// <summary>
        /// Test the property 'CenterOfMass'
        /// </summary>
        [Test]
        public void CenterOfMassTest()
        {
            // TODO unit test for the property 'CenterOfMass'
        }
        /// <summary>
        /// Test the property 'RateTable'
        /// </summary>
        [Test]
        public void RateTableTest()
        {
            // TODO unit test for the property 'RateTable'
        }

    }

}
