/* 
 * paccurate.io
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Box
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BoxTests
    {
        // TODO uncomment below to declare an instance variable for Box
        //private Box instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Box
            //instance = new Box();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Box
        /// </summary>
        [Test]
        public void BoxInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Box
            //Assert.IsInstanceOfType<Box> (instance, "variable 'instance' is a Box");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Subspace'
        /// </summary>
        [Test]
        public void SubspaceTest()
        {
            // TODO unit test for the property 'Subspace'
        }
        /// <summary>
        /// Test the property 'BoxType'
        /// </summary>
        [Test]
        public void BoxTypeTest()
        {
            // TODO unit test for the property 'BoxType'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'VolumeMax'
        /// </summary>
        [Test]
        public void VolumeMaxTest()
        {
            // TODO unit test for the property 'VolumeMax'
        }
        /// <summary>
        /// Test the property 'VolumeUsed'
        /// </summary>
        [Test]
        public void VolumeUsedTest()
        {
            // TODO unit test for the property 'VolumeUsed'
        }
        /// <summary>
        /// Test the property 'VolumeNet'
        /// </summary>
        [Test]
        public void VolumeNetTest()
        {
            // TODO unit test for the property 'VolumeNet'
        }
        /// <summary>
        /// Test the property 'VolumeRemaining'
        /// </summary>
        [Test]
        public void VolumeRemainingTest()
        {
            // TODO unit test for the property 'VolumeRemaining'
        }
        /// <summary>
        /// Test the property 'VolumeReserved'
        /// </summary>
        [Test]
        public void VolumeReservedTest()
        {
            // TODO unit test for the property 'VolumeReserved'
        }
        /// <summary>
        /// Test the property 'VolumeUtilization'
        /// </summary>
        [Test]
        public void VolumeUtilizationTest()
        {
            // TODO unit test for the property 'VolumeUtilization'
        }
        /// <summary>
        /// Test the property 'WeightUsed'
        /// </summary>
        [Test]
        public void WeightUsedTest()
        {
            // TODO unit test for the property 'WeightUsed'
        }
        /// <summary>
        /// Test the property 'WeightNet'
        /// </summary>
        [Test]
        public void WeightNetTest()
        {
            // TODO unit test for the property 'WeightNet'
        }
        /// <summary>
        /// Test the property 'WeightRemaining'
        /// </summary>
        [Test]
        public void WeightRemainingTest()
        {
            // TODO unit test for the property 'WeightRemaining'
        }
        /// <summary>
        /// Test the property 'WeightUtilization'
        /// </summary>
        [Test]
        public void WeightUtilizationTest()
        {
            // TODO unit test for the property 'WeightUtilization'
        }
        /// <summary>
        /// Test the property 'DimensionalWeight'
        /// </summary>
        [Test]
        public void DimensionalWeightTest()
        {
            // TODO unit test for the property 'DimensionalWeight'
        }
        /// <summary>
        /// Test the property 'DimensionalWeightUsed'
        /// </summary>
        [Test]
        public void DimensionalWeightUsedTest()
        {
            // TODO unit test for the property 'DimensionalWeightUsed'
        }
        /// <summary>
        /// Test the property 'Svg'
        /// </summary>
        [Test]
        public void SvgTest()
        {
            // TODO unit test for the property 'Svg'
        }
        /// <summary>
        /// Test the property 'CenterOfMassString'
        /// </summary>
        [Test]
        public void CenterOfMassStringTest()
        {
            // TODO unit test for the property 'CenterOfMassString'
        }
        /// <summary>
        /// Test the property 'DepthOrder'
        /// </summary>
        [Test]
        public void DepthOrderTest()
        {
            // TODO unit test for the property 'DepthOrder'
        }
        /// <summary>
        /// Test the property 'DepthOrderString'
        /// </summary>
        [Test]
        public void DepthOrderStringTest()
        {
            // TODO unit test for the property 'DepthOrderString'
        }

    }

}
