/* 
 * paccurate.io
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ItemProperties
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemPropertiesTests
    {
        // TODO uncomment below to declare an instance variable for ItemProperties
        //private ItemProperties instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ItemProperties
            //instance = new ItemProperties();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemProperties
        /// </summary>
        [Test]
        public void ItemPropertiesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemProperties
            //Assert.IsInstanceOfType<ItemProperties> (instance, "variable 'instance' is a ItemProperties");
        }


        /// <summary>
        /// Test the property 'RefId'
        /// </summary>
        [Test]
        public void RefIdTest()
        {
            // TODO unit test for the property 'RefId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'Sequence'
        /// </summary>
        [Test]
        public void SequenceTest()
        {
            // TODO unit test for the property 'Sequence'
        }
        /// <summary>
        /// Test the property 'Dimensions'
        /// </summary>
        [Test]
        public void DimensionsTest()
        {
            // TODO unit test for the property 'Dimensions'
        }
        /// <summary>
        /// Test the property 'CenterOfMass'
        /// </summary>
        [Test]
        public void CenterOfMassTest()
        {
            // TODO unit test for the property 'CenterOfMass'
        }
        /// <summary>
        /// Test the property 'Virtual'
        /// </summary>
        [Test]
        public void VirtualTest()
        {
            // TODO unit test for the property 'Virtual'
        }

    }

}
