/* 
 * paccurate.io
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PackResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PackResponseTests
    {
        // TODO uncomment below to declare an instance variable for PackResponse
        //private PackResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PackResponse
            //instance = new PackResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PackResponse
        /// </summary>
        [Test]
        public void PackResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PackResponse
            //Assert.IsInstanceOfType<PackResponse> (instance, "variable 'instance' is a PackResponse");
        }


        /// <summary>
        /// Test the property 'Boxes'
        /// </summary>
        [Test]
        public void BoxesTest()
        {
            // TODO unit test for the property 'Boxes'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Built'
        /// </summary>
        [Test]
        public void BuiltTest()
        {
            // TODO unit test for the property 'Built'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'LenBoxes'
        /// </summary>
        [Test]
        public void LenBoxesTest()
        {
            // TODO unit test for the property 'LenBoxes'
        }
        /// <summary>
        /// Test the property 'LenItems'
        /// </summary>
        [Test]
        public void LenItemsTest()
        {
            // TODO unit test for the property 'LenItems'
        }
        /// <summary>
        /// Test the property 'LenLeftovers'
        /// </summary>
        [Test]
        public void LenLeftoversTest()
        {
            // TODO unit test for the property 'LenLeftovers'
        }
        /// <summary>
        /// Test the property 'TotalCost'
        /// </summary>
        [Test]
        public void TotalCostTest()
        {
            // TODO unit test for the property 'TotalCost'
        }
        /// <summary>
        /// Test the property 'PackTime'
        /// </summary>
        [Test]
        public void PackTimeTest()
        {
            // TODO unit test for the property 'PackTime'
        }
        /// <summary>
        /// Test the property 'RenderTime'
        /// </summary>
        [Test]
        public void RenderTimeTest()
        {
            // TODO unit test for the property 'RenderTime'
        }
        /// <summary>
        /// Test the property 'TotalTime'
        /// </summary>
        [Test]
        public void TotalTimeTest()
        {
            // TODO unit test for the property 'TotalTime'
        }
        /// <summary>
        /// Test the property 'Leftovers'
        /// </summary>
        [Test]
        public void LeftoversTest()
        {
            // TODO unit test for the property 'Leftovers'
        }
        /// <summary>
        /// Test the property 'ItemSortUsed'
        /// </summary>
        [Test]
        public void ItemSortUsedTest()
        {
            // TODO unit test for the property 'ItemSortUsed'
        }
        /// <summary>
        /// Test the property 'BoxTypeChoiceGoalUsed'
        /// </summary>
        [Test]
        public void BoxTypeChoiceGoalUsedTest()
        {
            // TODO unit test for the property 'BoxTypeChoiceGoalUsed'
        }
        /// <summary>
        /// Test the property 'Scripts'
        /// </summary>
        [Test]
        public void ScriptsTest()
        {
            // TODO unit test for the property 'Scripts'
        }
        /// <summary>
        /// Test the property 'Styles'
        /// </summary>
        [Test]
        public void StylesTest()
        {
            // TODO unit test for the property 'Styles'
        }
        /// <summary>
        /// Test the property 'Svgs'
        /// </summary>
        [Test]
        public void SvgsTest()
        {
            // TODO unit test for the property 'Svgs'
        }
        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Test]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }

    }

}
