/* 
 * paccurate.io
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Pack
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PackTests
    {
        // TODO uncomment below to declare an instance variable for Pack
        //private Pack instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Pack
            //instance = new Pack();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Pack
        /// </summary>
        [Test]
        public void PackInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Pack
            //Assert.IsInstanceOfType<Pack> (instance, "variable 'instance' is a Pack");
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'LayFlat'
        /// </summary>
        [Test]
        public void LayFlatTest()
        {
            // TODO unit test for the property 'LayFlat'
        }
        /// <summary>
        /// Test the property 'Interlock'
        /// </summary>
        [Test]
        public void InterlockTest()
        {
            // TODO unit test for the property 'Interlock'
        }
        /// <summary>
        /// Test the property 'Corners'
        /// </summary>
        [Test]
        public void CornersTest()
        {
            // TODO unit test for the property 'Corners'
        }
        /// <summary>
        /// Test the property 'ItemSets'
        /// </summary>
        [Test]
        public void ItemSetsTest()
        {
            // TODO unit test for the property 'ItemSets'
        }
        /// <summary>
        /// Test the property 'BoxTypes'
        /// </summary>
        [Test]
        public void BoxTypesTest()
        {
            // TODO unit test for the property 'BoxTypes'
        }
        /// <summary>
        /// Test the property 'Boxes'
        /// </summary>
        [Test]
        public void BoxesTest()
        {
            // TODO unit test for the property 'Boxes'
        }
        /// <summary>
        /// Test the property 'UsableSpace'
        /// </summary>
        [Test]
        public void UsableSpaceTest()
        {
            // TODO unit test for the property 'UsableSpace'
        }
        /// <summary>
        /// Test the property 'ReservedSpace'
        /// </summary>
        [Test]
        public void ReservedSpaceTest()
        {
            // TODO unit test for the property 'ReservedSpace'
        }
        /// <summary>
        /// Test the property 'BoxTypeSets'
        /// </summary>
        [Test]
        public void BoxTypeSetsTest()
        {
            // TODO unit test for the property 'BoxTypeSets'
        }
        /// <summary>
        /// Test the property 'Eye'
        /// </summary>
        [Test]
        public void EyeTest()
        {
            // TODO unit test for the property 'Eye'
        }
        /// <summary>
        /// Test the property 'PackOrigin'
        /// </summary>
        [Test]
        public void PackOriginTest()
        {
            // TODO unit test for the property 'PackOrigin'
        }
        /// <summary>
        /// Test the property 'Zone'
        /// </summary>
        [Test]
        public void ZoneTest()
        {
            // TODO unit test for the property 'Zone'
        }
        /// <summary>
        /// Test the property 'Rules'
        /// </summary>
        [Test]
        public void RulesTest()
        {
            // TODO unit test for the property 'Rules'
        }
        /// <summary>
        /// Test the property 'Random'
        /// </summary>
        [Test]
        public void RandomTest()
        {
            // TODO unit test for the property 'Random'
        }
        /// <summary>
        /// Test the property 'N'
        /// </summary>
        [Test]
        public void NTest()
        {
            // TODO unit test for the property 'N'
        }
        /// <summary>
        /// Test the property 'RandomMaxDimension'
        /// </summary>
        [Test]
        public void RandomMaxDimensionTest()
        {
            // TODO unit test for the property 'RandomMaxDimension'
        }
        /// <summary>
        /// Test the property 'RandomMaxWeight'
        /// </summary>
        [Test]
        public void RandomMaxWeightTest()
        {
            // TODO unit test for the property 'RandomMaxWeight'
        }
        /// <summary>
        /// Test the property 'RandomMaxQuantity'
        /// </summary>
        [Test]
        public void RandomMaxQuantityTest()
        {
            // TODO unit test for the property 'RandomMaxQuantity'
        }
        /// <summary>
        /// Test the property 'Seed'
        /// </summary>
        [Test]
        public void SeedTest()
        {
            // TODO unit test for the property 'Seed'
        }
        /// <summary>
        /// Test the property 'SeedValue'
        /// </summary>
        [Test]
        public void SeedValueTest()
        {
            // TODO unit test for the property 'SeedValue'
        }
        /// <summary>
        /// Test the property 'ImgSize'
        /// </summary>
        [Test]
        public void ImgSizeTest()
        {
            // TODO unit test for the property 'ImgSize'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }
        /// <summary>
        /// Test the property 'IncludeScripts'
        /// </summary>
        [Test]
        public void IncludeScriptsTest()
        {
            // TODO unit test for the property 'IncludeScripts'
        }
        /// <summary>
        /// Test the property 'IncludeImages'
        /// </summary>
        [Test]
        public void IncludeImagesTest()
        {
            // TODO unit test for the property 'IncludeImages'
        }
        /// <summary>
        /// Test the property 'ImageFormat'
        /// </summary>
        [Test]
        public void ImageFormatTest()
        {
            // TODO unit test for the property 'ImageFormat'
        }
        /// <summary>
        /// Test the property 'CoordOrder'
        /// </summary>
        [Test]
        public void CoordOrderTest()
        {
            // TODO unit test for the property 'CoordOrder'
        }
        /// <summary>
        /// Test the property 'CohortPacking'
        /// </summary>
        [Test]
        public void CohortPackingTest()
        {
            // TODO unit test for the property 'CohortPacking'
        }
        /// <summary>
        /// Test the property 'CohortMax'
        /// </summary>
        [Test]
        public void CohortMaxTest()
        {
            // TODO unit test for the property 'CohortMax'
        }
        /// <summary>
        /// Test the property 'AllowableOverhang'
        /// </summary>
        [Test]
        public void AllowableOverhangTest()
        {
            // TODO unit test for the property 'AllowableOverhang'
        }
        /// <summary>
        /// Test the property 'PlacementStyle'
        /// </summary>
        [Test]
        public void PlacementStyleTest()
        {
            // TODO unit test for the property 'PlacementStyle'
        }
        /// <summary>
        /// Test the property 'ItemSort'
        /// </summary>
        [Test]
        public void ItemSortTest()
        {
            // TODO unit test for the property 'ItemSort'
        }
        /// <summary>
        /// Test the property 'ItemSortReverse'
        /// </summary>
        [Test]
        public void ItemSortReverseTest()
        {
            // TODO unit test for the property 'ItemSortReverse'
        }
        /// <summary>
        /// Test the property 'ItemInitialOrientationBestForBox'
        /// </summary>
        [Test]
        public void ItemInitialOrientationBestForBoxTest()
        {
            // TODO unit test for the property 'ItemInitialOrientationBestForBox'
        }
        /// <summary>
        /// Test the property 'ItemInitialOrientationPreferred'
        /// </summary>
        [Test]
        public void ItemInitialOrientationPreferredTest()
        {
            // TODO unit test for the property 'ItemInitialOrientationPreferred'
        }
        /// <summary>
        /// Test the property 'ItemOrientationSearchDepth'
        /// </summary>
        [Test]
        public void ItemOrientationSearchDepthTest()
        {
            // TODO unit test for the property 'ItemOrientationSearchDepth'
        }
        /// <summary>
        /// Test the property 'SequenceSort'
        /// </summary>
        [Test]
        public void SequenceSortTest()
        {
            // TODO unit test for the property 'SequenceSort'
        }
        /// <summary>
        /// Test the property 'SequenceHeatMap'
        /// </summary>
        [Test]
        public void SequenceHeatMapTest()
        {
            // TODO unit test for the property 'SequenceHeatMap'
        }
        /// <summary>
        /// Test the property 'MaxSequenceDistance'
        /// </summary>
        [Test]
        public void MaxSequenceDistanceTest()
        {
            // TODO unit test for the property 'MaxSequenceDistance'
        }
        /// <summary>
        /// Test the property 'BoxTypeChoiceStyle'
        /// </summary>
        [Test]
        public void BoxTypeChoiceStyleTest()
        {
            // TODO unit test for the property 'BoxTypeChoiceStyle'
        }
        /// <summary>
        /// Test the property 'BoxTypeChoiceLookahead'
        /// </summary>
        [Test]
        public void BoxTypeChoiceLookaheadTest()
        {
            // TODO unit test for the property 'BoxTypeChoiceLookahead'
        }
        /// <summary>
        /// Test the property 'BoxTypeChoiceGoal'
        /// </summary>
        [Test]
        public void BoxTypeChoiceGoalTest()
        {
            // TODO unit test for the property 'BoxTypeChoiceGoal'
        }
        /// <summary>
        /// Test the property 'BoxesPerItemSetMax'
        /// </summary>
        [Test]
        public void BoxesPerItemSetMaxTest()
        {
            // TODO unit test for the property 'BoxesPerItemSetMax'
        }
        /// <summary>
        /// Test the property 'ValueTiebreaker'
        /// </summary>
        [Test]
        public void ValueTiebreakerTest()
        {
            // TODO unit test for the property 'ValueTiebreaker'
        }

    }

}
