/* 
 * paccurate.io
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RateTable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RateTableTests
    {
        // TODO uncomment below to declare an instance variable for RateTable
        //private RateTable instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RateTable
            //instance = new RateTable();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RateTable
        /// </summary>
        [Test]
        public void RateTableInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RateTable
            //Assert.IsInstanceOfType<RateTable> (instance, "variable 'instance' is a RateTable");
        }


        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Test]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }
        /// <summary>
        /// Test the property 'Zone'
        /// </summary>
        [Test]
        public void ZoneTest()
        {
            // TODO unit test for the property 'Zone'
        }
        /// <summary>
        /// Test the property 'Rates'
        /// </summary>
        [Test]
        public void RatesTest()
        {
            // TODO unit test for the property 'Rates'
        }
        /// <summary>
        /// Test the property 'Weights'
        /// </summary>
        [Test]
        public void WeightsTest()
        {
            // TODO unit test for the property 'Weights'
        }
        /// <summary>
        /// Test the property 'PriceIncreaseRate'
        /// </summary>
        [Test]
        public void PriceIncreaseRateTest()
        {
            // TODO unit test for the property 'PriceIncreaseRate'
        }
        /// <summary>
        /// Test the property 'BasePrice'
        /// </summary>
        [Test]
        public void BasePriceTest()
        {
            // TODO unit test for the property 'BasePrice'
        }
        /// <summary>
        /// Test the property 'DimFactor'
        /// </summary>
        [Test]
        public void DimFactorTest()
        {
            // TODO unit test for the property 'DimFactor'
        }

    }

}
