/* 
 * paccurate.io
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Rule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RuleTests
    {
        // TODO uncomment below to declare an instance variable for Rule
        //private Rule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Rule
            //instance = new Rule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Rule
        /// </summary>
        [Test]
        public void RuleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Rule
            //Assert.IsInstanceOfType<Rule> (instance, "variable 'instance' is a Rule");
        }


        /// <summary>
        /// Test the property 'ItemRefId'
        /// </summary>
        [Test]
        public void ItemRefIdTest()
        {
            // TODO unit test for the property 'ItemRefId'
        }
        /// <summary>
        /// Test the property 'TargetItemRefIds'
        /// </summary>
        [Test]
        public void TargetItemRefIdsTest()
        {
            // TODO unit test for the property 'TargetItemRefIds'
        }
        /// <summary>
        /// Test the property 'Operation'
        /// </summary>
        [Test]
        public void OperationTest()
        {
            // TODO unit test for the property 'Operation'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Test]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }

    }

}
