/* 
 * paccurate.io
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Subspace
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubspaceTests
    {
        // TODO uncomment below to declare an instance variable for Subspace
        //private Subspace instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Subspace
            //instance = new Subspace();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Subspace
        /// </summary>
        [Test]
        public void SubspaceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Subspace
            //Assert.IsInstanceOfType<Subspace> (instance, "variable 'instance' is a Subspace");
        }


        /// <summary>
        /// Test the property 'OriginInParent'
        /// </summary>
        [Test]
        public void OriginInParentTest()
        {
            // TODO unit test for the property 'OriginInParent'
        }
        /// <summary>
        /// Test the property 'ParentBoxIndex'
        /// </summary>
        [Test]
        public void ParentBoxIndexTest()
        {
            // TODO unit test for the property 'ParentBoxIndex'
        }
        /// <summary>
        /// Test the property 'ParentItemIndex'
        /// </summary>
        [Test]
        public void ParentItemIndexTest()
        {
            // TODO unit test for the property 'ParentItemIndex'
        }

    }

}
